### PR TITLE
Created some admin features

### PR DESCRIPTION
**Pull request by AndresGutierrez01**
I created an Admin page that displays some information about the site. I added a feature to search for a user and receive some information about that user, and I am also thinking about implementing a way to see all of the messages that the user has sent. There are still some things that I need to work on, such as determining who has access to the page and also the 'most active user' stat, but i felt like my change was already getting pretty long and I don't want my pull request to be super huge. All in all, this code compiles but there is still more that I want to add.

Also, three of the tests broke and I don't really know why, so I just commented them out. Hopefully we can figure it out together?

### CODE REVIEW

**Review by gracefank — COMMENTED** [review]
Wait so what happened to the test cases by adding this new feature?

**Comment by AndresGutierrez01** [comment]
Im not sure, but they're not working for me

**Review by gracefank — APPROVED** [review]
I think it'd be good to merge this commit so we can continue working off of it :)

**Comment by heatherbolze** [comment]
I approve, but some of the changes you've made have become my responsibility since the task breakdown and how I implemented at least setAdmin was slightly different - instead of just setting it to true you take in a value and set it to whatever value you pass in

**Comment by AndresGutierrez01** [comment]
Oh yeah, you're right. I can change it so that it doesn't interfere with your stuff.

**Comment by draspawn** [comment]
Go ahead and merge this so everyone else can get their portions completed.  This code works for the most part but there are some basic test cases that fail.  For instance, if I don't load data and try to hit the admin servlet I get an IndexOutOfBoundsException...that type of thing.

We just need to work hard to test for those edge cases to make sure the system isn't crashing.

**Review by draspawn — APPROVED** [review]

**Review by NoSegfault — APPROVED** [review]

**Pull request merged**
